apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql
    name: mysql-pod
    envFrom:
    - configMapRef:
        name: db-config
    - secretRef:
        name: db-secret
    ports:
    - containerPort: 3306 # Expose port inside the container
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    run: mysql-pod
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
