apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: php-app
  name: php-app
spec:
  containers:
  - image: mihirmodi2561/phpapp
    name: php-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: php-app
  name: php-app-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: php-app
  type: NodePort
