apiVersion: v1
kind: Pod
metadata:
  labels:
    run: php-admin-pod
  name: php-admin-pod
spec:
  containers:
  - image: phpmyadmin
    name: php-admin-pod
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: php-admin-config
    - secretRef:
        name: php-admin-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: my-php-service
spec:
  type: NodePort
  selector:
    run: php-admin-pod
  ports:
  - protocol: TCP
    port: 8099       # External port
    targetPort: 80   # Container's port for phpMyAdmin
    nodePort: 30000  # Optional, or auto-assign
